
			<script>
				import { onMount, onDestroy } from 'svelte'
				import { browser } from '$app/environment'
				import { bbLookup, bbIniting, bbDebug } from '$lib/stores.js'
				import * as BB from 'babylonjs'
				import { createEventDispatcher } from 'svelte'
				

				// ================ QUICKLOOK ================

				/* 
					scene  * required 
					defaultRT  
					disableGammaTransform  
					doNotUseGeometryRendererFallback  
					excludedMaterials  
					excludedSkinnedMesh  
					mrtCount  
					renderTargets  
				*/

				// ================ CONSTRUCTOR PROPERTIES ================

				
				export let scene = undefined // [scene] * required
				// the scene
				

				// ================ CLASS INSTANCE ================

				export let instance = browser ? new BB.PrePassRenderer(scene) : {}

				// ================ ACCESSORS ================

				
				export let currentRTisSceneRT = undefined // [boolean] 
				// 
				

				export let enabled = undefined // [boolean] 
				// 
				

				export let isSupported = undefined // [boolean] 
				// 
				

				export let samples = undefined // [number] 
				// 
				

				// ================ PROPERTIES ================

				
				export let defaultRT = undefined // [prepassrendertarget] 
				// the render target where the scene is directly rendered
				

				export let disableGammaTransform = undefined // [boolean] 
				// set to true to disable gamma transform in prepass.can be useful in case you already proceed to gamma transform on a material leveland your post processes don't need to be in linear color space.
				

				export let doNotUseGeometryRendererFallback = undefined // [boolean] 
				// prevents the prepassrenderer from using the geometrybufferrenderer as a fallback
				

				export let excludedMaterials = undefined // [array] 
				// force material to be excluded from the prepasscan be useful when 
				

				export let excludedSkinnedMesh = undefined // [array] 
				// to save performance, we can excluded skinned meshes from the prepass
				

				export let mrtCount = undefined // [number] 
				// number of textures in the multi render target texture where the scene is directly rendered
				

				export let renderTargets = undefined // [array] 
				// all the render targets generated by prepass
				

				// ================ METHODS ================

				
				export let addEffectConfiguration = (...args) => instance.addEffectConfiguration(...args)

				export let bindAttachmentsForEffect = (...args) => instance.bindAttachmentsForEffect(...args)

				export let dispose = (...args) => instance.dispose(...args)

				export let getIndex = (...args) => instance.getIndex(...args)

				export let getRenderTarget = (...args) => instance.getRenderTarget(...args)

				export let markAsDirty = (...args) => instance.markAsDirty(...args)

				export let restoreAttachments = (...args) => instance.restoreAttachments(...args)

				export let setCustomOutput = (...args) => instance.setCustomOutput(...args)
				
				// ================ LIFECYCLE ================
				

				export let onMounted = () => {}
				export let onInited = () => {}
				export let onLoaded = () => {}

				const DEBUG = (...args) => $bbDebug ? console.log(`[${name}:PrePassRenderer]`, ...args) : null

				const self = !import.meta.env.SSR && arguments[0]
				$bbLookup.set( self, false )
				bbIniting.set( true )
				DEBUG('✨ initing')

				onMount( async e => {
					$bbLookup.set( self, true )
					DEBUG('🌱 mounted')
					let timeout = null
					onMounted(instance)
					const unsubscribe = bbIniting.subscribe( v => {
						if (timeout) clearTimeout( timeout )
						timeout = setTimeout( e => {

							$bbIniting = !Array.from($bbLookup.values()).every(v => v)
							DEBUG('🌿 inited')
							onInited(instance)

							if (!$bbIniting) {

												if (scene != undefined) instance.scene = scene?.instance || scene
				scene = instance.scene

				currentRTisSceneRT = instance.currentRTisSceneRT

				enabled = instance.enabled

				isSupported = instance.isSupported
				if (samples != undefined) instance.samples = samples?.instance || samples
				samples = instance.samples
				if (defaultRT != undefined) instance.defaultRT = defaultRT?.instance || defaultRT
				defaultRT = instance.defaultRT
				if (disableGammaTransform != undefined) instance.disableGammaTransform = disableGammaTransform?.instance || disableGammaTransform
				disableGammaTransform = instance.disableGammaTransform
				if (doNotUseGeometryRendererFallback != undefined) instance.doNotUseGeometryRendererFallback = doNotUseGeometryRendererFallback?.instance || doNotUseGeometryRendererFallback
				doNotUseGeometryRendererFallback = instance.doNotUseGeometryRendererFallback
				if (excludedMaterials != undefined) instance.excludedMaterials = excludedMaterials?.instance || excludedMaterials
				excludedMaterials = instance.excludedMaterials
				if (excludedSkinnedMesh != undefined) instance.excludedSkinnedMesh = excludedSkinnedMesh?.instance || excludedSkinnedMesh
				excludedSkinnedMesh = instance.excludedSkinnedMesh
				if (mrtCount != undefined) instance.mrtCount = mrtCount?.instance || mrtCount
				mrtCount = instance.mrtCount
				if (renderTargets != undefined) instance.renderTargets = renderTargets?.instance || renderTargets
				renderTargets = instance.renderTargets

								// ================ AFRAME PARENT ================

								if (autoParent && !parent) {
									let counter = autoParent
									let parentNode = fieldset
									while( counter > 0 ) {
										parentNode = parentNode.parentNode
										counter-=1
									}
									const parentComponent = $bbLookup.get( parentNode )
									if (parentComponent) {
										instance.parent = parentComponent.instance
										DEBUG('👩‍👦 parent')
									}
								}
								DEBUG('🌴 aframe')
								onLoaded(instance)
							}
						}, 10)
					})
				})


				onDestroy( async e => {
					DEBUG('🔥 destroyed')
					if (instance.dispose) instance.dispose()
				})


				export let autoParent = null
				let fieldset
			</script>
			<svelte:options accessors/>
			<fieldset bind:this={fieldset}>
				<slot />
			</fieldset>

			